# Generated by Django 5.2.5 on 2025-08-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
